{% set version = "2021.4" %}

package:
  name: sfepy
  version: {{ version }}

source:
  url: https://github.com/sfepy/sfepy/archive/release_{{ version }}.zip
  sha256: 4bb2609f838719993f33a5ce20b815a7f1771f18a883e959df2740b17d770e42

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - scipy
    - pytables
    - matplotlib-base
    - importlib_metadata
    - meshio 4.4.6
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - pyparsing
    - pytables
    - matplotlib-base
    - importlib_metadata
    - meshio 4.4.6
    - sympy
    - psutil

test:
  source_files:
    - run_tests.py
    - tests/
    - examples/
    - meshes/
  commands:
    - python run_tests.py --filter-none

about:
  home: http://sfepy.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "Simple finite elements in Python"
  description: >-
    SfePy is a software for solving systems of coupled partial
    differential equations (PDEs) by the finite element method in 1D,
    2D and 3D. It can be viewed both as black-box PDE solver, and as a
    Python package which can be used for building custom
    applications. The word simple means that complex FEM problems can
    be coded very easily and rapidly.
  doc_url: http://sfepy.org
  dev_url: https://github.com/sfepy/sfepy

extra:
  recipe-maintainers:
    - rc
    - wd15
