{% set version = "2023.1" %}

package:
  name: sfepy
  version: {{ version }}

source:
#  url: https://github.com/sfepy/sfepy/archive/release_{{ version }}.zip
#  sha256: 2bb2fa068839a0404ef674effe1148c1c02b8b976e1d16ac3db59626999c76f7
  url: https://github.com/yosefm/sfepy/archive/refs/heads/numpy-distutils-byebye.zip
  sha256: f58ddcc8917b04371a96e9e6ccfa5cd782c78dafbb1c8e36944cb427ac06c680

build:
  number: 0
  entry_points:
    - sfepy-convert = sfepy.scripts.convert_mesh:main
    - sfepy-mesh = sfepy.scripts.gen_mesh:main
    - sfepy-probe = sfepy.scripts.probe:main
    - sfepy-run = sfepy.scripts.simple:main
    - sfepy-test = sfepy.scripts.run_tests:main
    - sfepy-view = sfepy.scripts.resview:main
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - scikit-build >=0.16.7
    - setuptools >=46.4
    - pip
    - cython
    - numpy >=1.17
    - scipy
    - pytables
    - matplotlib-base
    - importlib_metadata
    - meshio 4.4.6
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - pyparsing
    - pytables
    - matplotlib-base
    - importlib_metadata
    - meshio 4.4.6
    - sympy
    - psutil

test:
  requires:
    - pytest
  source_files:
    - meshes/
  commands:
    - python -c "import sfepy, sys; sys.exit(sfepy.test())"

about:
  home: http://sfepy.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "Simple finite elements in Python"
  description: >-
    SfePy is a software for solving systems of coupled partial
    differential equations (PDEs) by the finite element method in 1D,
    2D and 3D. It can be viewed both as black-box PDE solver, and as a
    Python package which can be used for building custom
    applications. The word simple means that complex FEM problems can
    be coded very easily and rapidly.
  doc_url: http://sfepy.org
  dev_url: https://github.com/sfepy/sfepy

extra:
  recipe-maintainers:
    - rc
    - wd15
